### ISSUE TITLE
Request Not found

### ISSUE THREAD

**Issue by moreiraandre** [AjinkyaBijwe/VideoWEBRTC#3]
after the requisition of return requests, did I do something wrong?

![error-req](https://user-images.githubusercontent.com/11823149/52905866-48e73e00-321f-11e9-9bf6-2c8b623f9cf0.png)

**Comment by AjinkyaBijwe** [comment]
The pubnub sdk used for this app is dead app will no longer work without proper edits

**Comment by cescfazhaz** [comment]
hello dear friend... I from Chile... I have a question.... can you help me please.... is very important for me... I am a student .... and I need solve a  
doubt... where can I find the step 7) Run videowe3_ajinkya.sql file in videowe3_ajinkya database provided in the Config folder of project mainv10/config 
Because I cant see the captcha and I cant built users 
I hope that you can help me please... Thanks you so much. I am your fan

**Comment by AjinkyaBijwe** [comment]
@cescfazhaz this project is actually not working as apis and sdks used for this is expired long back use this project instead
https://github.com/pubnub/webrtc-chat
